root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp ./cmd/web/main.go"
  bin = "tmp/main"
  full_bin = ""
  send_interrupt = false
  kill_delay = "1s"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "assets", "testdata", "postgres_data", "redis_data"]
  include_dir = []
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  delay = 0
  stop_on_error = false
  log = ""

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
